version: '2'
services:
  api:
    build: .
    volumes:
      - ./api:/webapps/perseids
    command: bash -c "ls -la && mix deps.get && npm install && mix ecto.create && mix phx.server"
    # command: bash -c "mix deps.get && npm install && mix ecto.create && MIX_ENV=prod PORT=4000 iex -S mix phoenix.server"
    # command: bash -c "sleep 100000"
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
      - mongo

  # ====================
  mongo:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - ./dockerdata/mongodb:/data/db
