version: '2'
services:
  api:
    build: .
    volumes:
      - ./api:/webapps/perseids
    command: bash -c "mix deps.get && npm install && mix ecto.create && mix compile && mix phoenix.server"
    env_file:
      - .env
    ports:
      - 101:4000
    depends_on:
      - mongo
    restart: always

  # ====================
  mongo:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - ../_data/mongodb:/data/db
    restart: always
