#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    machine: true
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/app
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run:
          name: Install cURL
          command: sudo apt-get update && sudo apt-get -y install curl
      - run:
          name: Install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: cp .env.circle-ci .env
      - run:
          name: Run application containers
          command: docker-compose up -d
      - run:
          name: Init MongoDB
          command: docker-compose exec mongo mongo --eval "$(< prepare_mongo.js)"
      - run:
          name: Create test DB
          command: docker-compose exec mongo mongo --eval "db.copyDatabase('perseids', 'perseids_test')"
      - run:
          name: Mix Deps
          command: docker-compose exec api bash -c "mix deps.get"
      - run:
          name: Run tests
          command: docker-compose exec api bash -c "MIX_ENV=test mix test"

