#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      - image: debian:9.2
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/app
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run:
          name: Install curl
          command: sudo apt-get update && sudo apt-get install curl
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run: cp .env.sample .env
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose -f docker-compose-production.yml -d

